adaptor_option: '--illumina'
max_multiMapping: 20
num_cores: 4
Unmapped_option: 'Fastx' 
quantMode: 'TranscriptomeSAM'
alignIntronMax: 1
EndsType: "EndToEnd"
winAnchorMultimapNmax: 100
seedSearchStartLmax: 20
sjdbOverhang: 43
sjdbGTFfile: '-'
SAMat: 'Standard'