adaptor_option: '--illumina'
max_multiMapping: 20
num_cores: 4
Unmapped_option: 'Fastx' 
quantMode: 'TranscriptomeSAM'
alignIntronMax: 1
EndsType: "EndToEnd"
winAnchorMultimapNmax: 100
seedSearchStartLmax: 20
sjdbOverhang: 43
outWigType: 'None'
sjdbGTFfile: '/local/storage/maa7095/references/human/gencode_primary/MANE_ref/MANE.GRCh38.v1.2.ensembl_genomic.gtf'
SAMat: 'Standard'
